#+title: Git
#+LANGUAGE: en
A new Git documentation using [[https://github.com/progit/progit2][ProGit2]] as source.

* Config & settings
#+begin_src bash
git config --list --show-origin # Show all settings
#+end_src
** User infos
#+begin_src bash
git config <flags> <variable.suffix> <infos>
#+end_src
*** Name
#+begin_src bash
git config --global user.name [<username>]
git config --global user.email [<mail.address>]
#+end_src
*** Email
*** Editor
#+begin_src bash
git config --global core.editor emacs # Must provide full path on Windows
#+end_src

#+RESULTS:
** branch config
[[*set name to default branch][set name to default branch]] 
* Repo
** Initialyse
#+begin_src bash
cd ~/your/path/for/your/repo
git init
#+end_src
** Adding file / Stagging
#+begin_src bash
git add <file>
#+end_src
** Unstaging file
#+begin_src bash
$ git reset HEAD <file>
#+end_src
** Remove file
#+begin_src bash
rm <file_name>
git rm [<file_name>...]         # The tree dots maining that it can be repeat
#+end_src
** Moving file
#+begin_src bash
git mv <source> <destination>
#+end_src
** [[*changes][Checking changes]]
** Remove stagged
#+begin_src bash
git rm [--cached] [<pathspec>...]
#+end_src
** Commit
*** Commit changes
#+begin_src bash
git commit -m "<msg>"       
#+end_src
*** Undo commit
Rewrite commit text
#+begin_src bash
git commit --amend
#+end_src

Undo
#+begin_src bash
$ git reset --soft HEAD~1 # ~1 for one previous commit
#+end_src
*** Link an commit to a issue
Just include #xxx in your commit message to reference an issue without closing it.

With new GitHub issues 2.0 you can use these synonyms to reference an issue and close it (in your commit message):

fix #xxx
fixes #xxx
fixed #xxx
close #xxx
closes #xxx
closed #xxx
resolve #xxx
resolves #xxx
resolved #xxx
You can also substitute #xxx with gh-xxx.

Referencing and closing issues across repos also works:

fixes user/repo#xxx
Check out the documentation available in their Help section.
Source: [[https://stackoverflow.com/questions/1687262/link-to-the-issue-number-on-github-within-a-commit-message][StackOverflow]]
** Checking
*** changes
#+begin_src bash
git diff
#+end_src
*** status
#+begin_src bash
git status
#+end_src
*** history or logs
#+begin_src bash
git log
git log --patch                 # Show the diff introduced in each commits (see ProGit2 Viewing the Commit History)
#+end_src
** Pushing
*** Undo pushing
#+begin_src bash
$ git revert HEAD
#+end_src
* Branch
** Create a branch & switch
#+begin_src bash eval: no
git checkout -b <branch/name>
git push -u origin <branch/name>
# Using -u make a link between the local & the remote branch. Without that, branches will be unlinked
git branch -vv                  # Verify links
#+end_src
** set name to default branch
#+begin_src bash
git config --global init.defaultBranch <branch/name>
#+end_src*
** Link a branch
Even if commits are already mades on branch
#+begin_src bash eval: no
git push -u origin <branch/name>
#+end_src
** Update branch (pull & rebase)
#+begin_src bash
git pull
git rebase
#+end_src
** Force to update a file
#+begin_src bash
git checkout master -- <path/to/file>
git commit -m "Reset <file> to match master version"
#+end_src
* [?] Issue
Don't know if it is his right place to be here.
** Link an commit to a
