#+title: Llm
#+subtitle: Large language model usage
#+language: en
* MPC
Model Context Protocol Server
* Quantization
** TODO Pre-requisit
** TODO Knowing matrics
** TODO How to an LLM works
** Mathematical relation
$$x = s \cdot (q - Z)$$
** [?] $S$ (Scale Factor): A positive floating-point number that determine the "step size" of the quantization levels.
** [?] $Z$ (Zero-point): An integer that ensures the floating-point value $0.0$ maps exactly to a representable integer (crucial for padding and ReLU).
** Symmetric Quantization: A simplified version where $Z = 0$. This is faster for computation but can be less precise if the weight distribution is skewed.
** Quantization Granularity

* Agent
** Dexter
See also : [[https://github.com/virattt/dexter][Dexter repo]]
An financial agent
** GeminiCLI
*** Commands
- */extensions list* :: view all isntalled extesions
- /skills list :: Manage availabhle skills
- /hooks panel :: Visualise active hooks

*** Update gemini cli
#+begin_src bash
npm install -g @google/gemini-cli@latest
#+end_src

*** Sandbox mode
*** User settings
[[~/.gemini/settings.json]]
#+begin_src json
"tools": {
    "sandbox": "docker"
  }
#+end_src
*** Workspace settings
[[.gemini/setttings.json]] (in your projecth)
*** Environnement variable
=GEMINI_SANDBOX=
*** Commad-line flag
#+begin_src bash
gemini -s
#+end_src

*** Extensions
*** [[file:MCP.org][MCP servers (Model Context Protocol)
]]Allows the model to interact with externals APIs, databases, or locales applications.
*** Agent skills
Directories of expertise. The model "activates" these on-demand when it identifies a matching task, which saves context tokens.
*** Hooks
Scripts that run at specific points in the agent's lifecycle (e.g., before executing a tool to validate arguments or after a model response to filter content).
*** Custom Commands
User-defined shortcuts (e.g., /my-action) triggered prompt or shell commands
*** Context Files
(GEMINI.md): Instructions that define the "personnality" loaded automatically at each startup session.
*** LIST
*** Gemini-Kit Team of agents
[[https://github.com/nth5693/gemini-kit]]
** Ollama
*** Logs
#+begin_src bash
nvim ~/.ollama/logs
#+end_src
*** Set path to model
#+begin_src bash
launchctl setenv OLLAMA_MODELS "/Volumes/T7 Shield/ARCH/MACOS/INFOR/MODELS"
export OLLAMA_MODELS="/path/to/your/models" #in .zshrc
#+end_src




