#- name: Installation d'Immich
#
#  host: myhosts
#  tasks:
#
#    # - name: Installation prérequise du cœur ansible pour docker
#    #   ansible.builtin.
#    # Créer un dossier pour l'installation
#  - name: Create an main immich directory
#       ansible.builtin.file:
#        path: ~/INFOR/CODE/IMMICH
#    - name: Create the immich instance directory
#       ansible.builtin.file:
#         path: ~/INFOR/CODE/IMMICH/immich-app
#
#     # Télécharger le logiciel immich
#    - name: Get docker file
#       ansible.builtin.get_url:
#         url: https://raw.githubusercontent.com/immich-app/immich/main/install.sh
#    - name: Get compose file
#       ansible.builtin.get_url:
#         url: wget -O .env https://github.com/immich-app/immich/releases/latest/download/example.env
#
#     # Modif de la config
#     #
##     - name: Replace one variable
##       ansible.builtin.replace:
##         path: ~/INFOR/DOCU/ANSIBLE/IMMICH/example.env
##         regexp: '^UPLOAD_LOCATION=.*$'
##         replace: 'UPLOAD_LOCATION=./Librairie'
#    - name: Replace multiples variables
#
#      ansible.builtin.replace:
#        path: ~/INFOR/DOCU/ANSIBLE/IMMICH/example.env
#        regexp: "{{item.regex}}"
#        replace: "{{item.replace}}"
#      loop:
#        - {regex: '^UPLOAD_LOCATION=.*$', replace: 'UPLAOD_LOCATION=./Librairie'}
#        - {regex: '^DB_DATA_LOCATION=.*$', replace: 'DB_DATA_LOCATION=./Database'}
#
#     - name: run docker compose
#       community.docker.docker_container:
#         name: immich
#         image:
#         compose_file: ~/INFOR/DOCU/ANSIBLE/IMMICH/docker-compose.yml
---
- name: Installation d'Immich
  hosts: all
  tasks:

    - name: Create an main immich directory
      ansible.builtin.file:
        path: ~/INFOR/DOCU/ANSIBLE/IMMICH
        state: directory

    - name: Create the immich instance directory
      ansible.builtin.file:
        path: ~/INFOR/DOCU/ANSIBLE/IMMICH/immich-app
        state: directory

    - name: Get docker compose file
      ansible.builtin.get_url:
        url: https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
        dest: ~/INFOR/DOCU/ANSIBLE/IMMICH/docker-compose.yml

    - name: Get env file
      ansible.builtin.get_url:
        url: https://github.com/immich-app/immich/releases/latest/download/example.env
        dest: ~/INFOR/DOCU/ANSIBLE/IMMICH/example.env

    - name: Replace multiples variables
      ansible.builtin.replace:
        path: ~/INFOR/DOCU/ANSIBLE/IMMICH/example.env
        regexp: "{{ item.regex }}"
        replace: "{{ item.replace }}"
      loop:
        - { regex: '^UPLOAD_LOCATION=.*$', replace: 'UPLOAD_LOCATION=./Librairie' }
        - { regex: '^DB_DATA_LOCATION=.*$', replace: 'DB_DATA_LOCATION=./Database' }

#        - name: Run docker compose
#      community.docker.docker_compose_v2:
#        project_src: ~/INFOR/DOCU/ANSIBLE/IMMICH
#      register: output
    - name: start docker
      ansible.builtin.command: docker compose up -d
