#+title: Dns
#+subtitle: Domain Name System
#+LANGUAGE:en
#+begin_quote
[!INFO]
A instance/server who store an address for each public ip adress.
#+end_quote
See on [[https://wiki.archlinux.org/title/Domain_name_resolution#:~:text=The%20DNS%20protocol,hijacking%2E][Arch Linux Wiki: DNS]]
#+begin_src 
The DNS protocol (Do53) is unencrypted and does not account for confidentiality, integrity or authentication, so if you use an untrusted network or a malicious ISP, your DNS queries can be eavesdropped and the responses manipulated. Furthermore, DNS servers can conduct DNS hijacking. 
#+end_src
* Fondamentals
** For DNS
*** TTL
=Time to live= is the longevity of a domain name in cache of an DNS system.
*** Recursive resolution
Is the whol path of an DNS request trough the entire DNS network. Computer => Internet Box => FAI => DNS server who store TLD => DNS server who handle the domain name zone.
** For Name system
*** TLD
=Top level domain= are the =.com= that you can find in an adress.
**** Whereis
There is a list of server who store a precise TLD (for eg: .com)
**** TLD server
For each request, TLD server can localize who manage the requested domain name zone
* Clear cache & restart DNS
Debian-based
#+begin_src bash :eval no
# Clear cache
sudo resolvectl flush-caches

# Verify if cashe is clear
sudo resolvectl statistics      # Current cache Size must be 0
#+end_src
* Debug dns resolutions
** Dig
#+begin_src bash :eval no
dig <example.com> any
#+end_src
** Can't connect trough the web page
*** Dig dns resolution if working
#+begin_src bash :eval no
dig <dns.resolution>
#+end_src
*** Adding to hosts the resolution
#+begin_src bash :eval no
# On MacOS
sudo echo "192.168.x.x    serv3.server.cloud" >> /etc/hosts
#+end_src
*** Clear DNS cache
#+begin_src bash :eval no
# On MacOS
sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder
#+end_src
#+begin_src bash :eval no
# On Linux
sudo systemd-resolve --flush-caches ou reboot
#+end_src
*** Dig dns resolution if working
#+begin_src bash :eval no
dig <dns.resolution>
#+end_src

