#+title: Nfs
See also : [[https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/6/html/storage_administration_guide/ch-nfs][Redhat NFS documentation]]
* Network File System
* Versions
Theres are 3 versions of NFS :
** NFSv2 (older but wildely supported)
*** TCP
Optionnal
** NFSv3 (newer and support asynchronous)
*** TCP
Optionnal
** NFSv4 (use TCP)
*** TCP
Use it
* Download
** Server
#+begin_src bash
$ sudo apt-install nfs-kernel-server
#+end_src
** Client
#+begin_src bash
$ sudo apt install nfs-common
#+end_src
* Config
** Server
*** Approriate access and permissiosn
For example purposes
#+begin_src bash
$ sudo chown root:staff /nfs/exports/myshare
$ sudo chmod 775 /nfs/exports/myshare
#+end_src
*** Editing config
#+begin_src bash

# In /etc/exports
/nfs/exports/myshare 192.168.122.0/24(rw,sync,no_subtree_check)
#+end_src
*** Reload config
#+begin_src bash
sudo exportfs -arv
#+end_src
*** Configure firewall
Only if =firewalld= run.
#+begin_src bash
$ sudo firewall-cmd --add-service nfs --permanent
$ sudo firewall-cmd --reload
#+end_src
** Client
*** Create a local mount point and mount the NFS share using the server’s IP address and the shared directory path
#+begin_src bash
$ sudo mkdir /nfs/imports/myshare
$ sudo mount -t nfs 192.168.122.17:/nfs/exports/myshare /nfs/imports/myshare
#+end_src
* Warns
#+begin_quote
[!WARNING]
In order for NFS to work with a default installation of Red Hat Enterprise Linux with a firewall enabled, configure IPTables with the default TCP port 2049. Without proper IPTables configuration, NFS will not function properly.
The NFS initialization script and rpc.nfsd process now allow binding to any specified port during system start up. However, this can be error-prone if the port is unavailable, or if it conflicts with another daemon.
#+end_quote
* Start
** Found [[https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/6/html/storage_administration_guide/ch-nfs#s2-nfs-how-daemons][here]] (not sure about the infos)
#+begin_src bash
$ service nfs start
#+end_src
** Verify if NFS service run
#+begin_src bash
$ systemctl status nfs-kernel-server
#+end_src
