#+title: Provider
[[https://docs.flutter.dev/data-and-backend/state-mgmt/simple][doc]]

* Principes
Provider sert à gérer l'état des widgets en évitant à l'utilisateur de gérer les ~callbacks~ (c'est un retour de l'informations au dessus)ou les ~InheritedWidgets~ (les widgets sans parents).
** Le cycle "Action => Donnée => Affichage"
** Action
Utilisateur tappe un nombre
** Donnée
Mettre à jour la variable (rôle de =notifyListeners()=)
** Afficher
Flutter entend =notifyListeners=, regarde quels widgets sont branchés sur ce modèle, et les redessine instantanément
** Read vs Watch
** Watch (Guetter)
=watch=
Utilisation dans l'affichage. Le widget surveille la donnée, si elle bouge: reconstruction immédiate.
#+begin_src dart
final value = context.watch<T>();
#+end_src
** Read
=read=
Utilisation pour une action ponctuelle (clic surun bouton "Valider").
Le widget dit donne la valeure
#+begin_src dart
final value = context.read<T>();
#+end_src
* Problèmes
** Accéder à une variable n'importe où
Discussion tirée de Gemini. Il m'a indiquer comment récupérer et lire n'importe quelle variable en utilisant Provider. Il ne faut PLUS que ce cas de figure se reproduise. Cet example à pour but d'éviter que cette situation ne se reproduise.
*** Créer la classe qui tiendra les données
#+begin_src dart
class DataModel extends ChangeNotifier{
  // Déclarer le nom
  String? _exampleString;

  // Accéder à la variable pour une lecture
  String? get exampleString => _exampleString;

  // Fonction appelée quand l'utilisateur clique
  void updateString (String? newValue) {
    _exampleString = newValue;
    notifyListeners(); // Dit à toute l'app : "Hé, ça a changé, mets-toi à jour."
    /// Donc la variable _exampleString stockera la donnée mise à jour grâce à Notify Listeners.
  }
}
#+end_src
*** Faire les calculs dans la pool
#+begin_src dart
class DataModel extends ChangeNotifier{
  String? _exampleString;
  String? get exampleString => _exampleString;

  // Faire les calculs dans une variable
  double get exampleType {
    switch (_selection) {
      case "Noir":
      return 0.18;
      case "Lait":
      return 0.22;
      case "Noir/Lait":
      return 0.20;
      case "Blanc":
      return 0.23;
      case "Autre":
      default: // important si selection est null
      return 0.0;
    }
  }
  
  void updateString (String? newValue) {
    _exampleString = newValue;
    notifyListeners();
  }
}
#+end_src
*** Dire à l'application que la "pool" existe
L'on doit entourer l'application avec ce =Provider=
#+begin_src dart
void main() {
  runApp(
    ChangeNotifierProvider(
      create: (context) => DataModel(),
      child: const myApp(),
    )
  )
}
#+end_src
*** Envoyer la donnée depuis le Widget de sélection
#+begin_src dart
/// Par exemple
/// Dans la fonction onSelected du ChoiceChip :
onSelected: (bool selected) {
  final newValue = selected ? chocolateType[index] : null;
  // Envoyer l'info au provider Provider.of<DataModel>(context, listen: false).updateString(newValue);
}
#+end_src
*** Utiliser la valeur n'importe où
Attention, ne fonctionne que dans le cas d'un widget qui possède un context. Dans une classe dart, le context ne fonctionnera pas.
Ne pas hésiter à faire les calculs dans la =pool= montrée au début. Comme ça tout est déjà fait.
#+begin_src dart
final selection = Provider.of<DataModel>(context, listen: false).exampleString;
if (selection == null) {
  selection == "Noir" 
} else if (selection == "Noir") {
  print("C'est intense !")
} else if (selection -- "Lait") {
// Faire autre chose
}
#+end_src

