#+title: Kubernetes
*   Lignes directrices de Kubernetes
Kubernetes permet la virtualisation de programme dans un serveur. De manière sécurisé. Il permet aussi de containariser.

* Kubernetes tools
Kubernetes s'utiliser avec des outils, comme ~kubeadm~, ~kubectl~ et ~kubelet~.
**  Kubeadm
C'est un outil de ligne de commande, utilisé pour la configuration initiale d'un kluster. Et dans l'intialisation des *nodes*. Il se charge, de la mise en place du kluster en plusieurs points dont :
- Création des certificats de sécurité
- Configuration du panel des composants
- Configuration du panel de networking
- Mise en place de meilleurs pratiques de sécurités
** kubectl
C'est aussi un outil en ligne, mais il va s'occuper de la gestion des container et des applications qui sont installés, tout au long du fuctionnement de Kubernetes.
- Execution des programmes, et des services au sein d'un kluster
- Mise à jour des systèmes d'informations (logs)
- Effectue du deboguage.
- MàJ des configs des applications.
** kubelet
Le kubelet est un système qui gère les nodes, comme une armoire contenant des serveurs (les nodes).
- Il communique entre l'API server et les nodes

*   Vocabulaire
- *Kluster* Un kluster est une sorte de machine virtuelle qui garde, et fait tourner un nombre de logiciels et programmes donnés, il permet de restreindre et de confiner un logiciel.
- *Node* Une sorte de machine à l'intérieur d'un kluster, cela peut être une machine virtuelle ou réelle. Un node renferme un Kubelet qui fait fonctionner des programmes.
- *Controle plane* Cerveau d'un kluster, il gère les sous programmes du kubernetes dont les Nodes, le ETCD, et biensûr l'API de serveur de Kubernetes qui va gérée toutes les demandes.
- *ETCD* C'est la base de donnée intégrée de Kubernetes.
- *Pods* Les pods sont des baleines ou des cargos qui stockes plusieurs container.
- *workload* Application qui tourne dans un cluster kubernetes
- *object* Une entitée qui représente l'état du cluster.
*   Architecture Kubernetes

[[https://kubernetes.io/images/docs/kubernetes-cluster-architecture.svg][Main architecture of kubernetes]]
**  Node
~.json~
#+begin_src json
{
  "kind": "Node",
  "apiVersion": "v1",
  "metadata": {
    "name": "10.240.79.157",
    "labels": {
      "name": "my-first-k8s-node"
    }
  }
}
#+end_src
 - Le nom d'un *node* doit être valide en suivant les règles du [[https://kubernetes.io/docs/concepts/overview/working-with-objects/names#dns-subdomain-names][DNS subdomain name]]

***  Types de déploiements
#+begin_quote
Pour ajouter un node au cluster, il y a deux manières de faire:
 1. Le *kubelet* sur un node (en self register) qui s'est lui-même register à l'*API server*
 2. Un humain qui ajoute lui-même le node.
Après cette création, le ~controle plane~ va chercher si le node est valide:
 1. Si il est ~register~ à l'*API server*.
 2. Si il est en bonne santée (touts les services qu'il contient: *kuberproxy* etc...) sinon, il va l'ignorer.
Cependant, il va constamment chercher à voir si le node deviens en bonne santée. Pour éviter cette recherche.
Il faut supprimer le node.
#+end_quote
*** Création automatique / self registration
Il semblerai que les nodes ai des ~flags~ qui définissent leurs comportememtn.
    Flags:
    ~--register-node~ (is true, par défaut)
    le kubelet va tenter une ~self registration~ auprès de l'*API server*.
**** Liste d'options par default pour une self registration
- ~--kuberconfig~ Chemin d'accès des identifiants pour s'ientifier lui-même à l'API server.
- ~--registernode~ S'enregistre automatiquement à l'API server.
- ~--node-ip~ Séparé par virgule, liste des adresses IP pour le node. Il sert à selectionner une adresse spécifique, si rien n'est spécifier
  alors il va utilise celle par default.
- ~--node-status-update-frequency~ Qui peut régler la fréquence de vérification de l'étatu du node pour l'API server.
**** Manual registration
Qui permet de créer et de modifier manuellement un node.
#+begin_quote
⚠️ Quand l'on créer le node manuellement, il faut spécifier le  ~--node-register:false~
- Mais l'on peut aussi modifier le node sans regarder l'état du ~--node-register~
#+end_quote
Rendre le node ~unshedulable~ pour éviter le placement prévu de nouveaux *pods* dans le node.
En lancant cette commande :
~$ kubectl cordon $NODENAME~

**  Communication beetwen Nodes and the Control Plane


* Exemples
**   Configuration simpliste d'un pod
#+begin_src yaml
apiVersion: v1
kind: Pod
metadata:
  name: mon-pod
spec:
  containers:
  - name: mon-conteneur
    image: nginx
#+end_src
* Installer Kubernetes
[[https://kubernetes.io/fr/docs/setup/production-environment/tools/kubeadm/install-kubeadm/][Documentation d'installation sous Debian]]
