#+title: Ansible
* [[https://docs.ansible.com/ansible/latest/getting_started/get_started_inventory.html][Inventory]]
- L'inventaire ~inventory.ini~ (ou .yaml) regroupe les ~nodes~ du projet (les points d'accès, ex: serveurs).
- Utiliser le format de fichier ini est plus court que la syntaxe yaml mais sur le long terme c'est mieux yaml

  #+begin_src ini
[hosts]
192.1.0
102921.9208.90218 #titre d'exemple
  #+end_src

#+begin_src yaml
myhosts:
  hosts:
    my_host_01:
      ansible_host: 192.0.2.50
    my_host_02:
      ansible_host: 192.0.2.51
    my_host_03:
      ansible_host: 192.0.2.52
#+end_src
** Vérifier son ~inventory~
#+begin_src bash
$ ansible-inventory -i inventory.ini --list
#+end_src
** Ping
#+begin_src bash
$ ansible nomDuFichierInventaire -m ping -i inventory.ini
#+end_src
* Playbooks
** Guide
  #+begin_example yaml
  --- #start
- name: This is a example
  ... #end

  #+end_example
  - Indentation via ~espaces~
** Différents concepts
- *Hosts* : le serveur géré qui va effectuer les tâches
- *Tasks* l'opération qui va être menée grâce aux modules Ansibles, en passant par des options
- *become* l'élécation des privilèges dans les *playbooks*
- *role* le role est comme un morceau de code (un fichier), il permet de gérer des actions plus complètes.
    #+begin_src
- name: Install web server
 hostst: web_servers
 roles:
 - nginx
    #+end_src

#+begin_example
L'ordre des contenus est important
Un playbooks doit être *idempotent*
#+end_example

#+begin_src
---
- name: Apache server installed
  hosts: web
  become: true
  tasks:

  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest

  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started

  - name: copy index.html
    copy:
      src: web.html
      dest: /var/www/html/index.html
#+end_src
** Création et structuration des dossiers et des fichiers
*** Définir "play"
#+begin_src yaml
---
- name: Apache server installed
 hosts: node1
 become: yes #toujours ajouter pour les privilèges
#+end_src
***   Définir "tasks"
#+begin_src yaml
---
- name: Apache server installed
  hosts: node1
  become: yes
  tasks:

    - name: Install Apache
      ansible.builtin.dnf:
        name: httpd
#+end_src
** Cycle de creation d'un playbook
1. Type "ansible module install package" into a search engine
2. Open the docs.ansible.com result that looks most helpful
3. Read through available parameters and the (often helpful) examples at the bottom
4. Copy an example into my playbook and modify parameters as needed
5. Go back to step 1, searching for the next task (e.g. "ansible module template file")
** LOOPS
#+begin_src yaml
- name: Remplacer plusieurs variables
  ansible.builtin.replace:
    path: ~/INFOR/DOCU/ANSIBLE/IMMICH/example.env
    regexp: "{{ item.regex }}"
    replace: "{{ item.replace }}"
  loop:
    - { regex: '^UPLOAD_LOCATION=.*$', replace: 'UPLOAD_LOCATION=./Librairie' }
    - { regex: '^DB_HOST=.*$',           replace: 'DB_HOST=db.example.local' }
    - { regex: '^DB_PORT=.*$',           replace: 'DB_PORT=5432' }
#+end_src

* Ansible Role
- Les roles sont une façon d'organiser ses packages de code pour qu'ils soit réutilisable.
Ils sont utilisé pour gérer des charges complexes et les roles peuvent être utilisé dans des playbooks.
- *Analogie :* Un playbook est une liste de directive et un role et un composant de cette liste.
** Structure et dossier
Un role ansible à une structuration de dossier spéciale. Il comporte normalement un certains nombre de dossiers, cependant si ils ne sont pas utilisés ils ne sont pas nécéssaires.
***   Organisation
#+begin_src
roles/
    common/               # this hierarchy represents a "role"
        tasks/            #
            main.yml      #  <-- tasks file can include smaller files if warranted
        handlers/         #
            main.yml      #  <-- handlers file
        templates/        #  <-- files for use with the template resource
            ntp.conf.j2   #  <------- templates end in .j2
        files/            #
            bar.txt       #  <-- files for use with the copy resource
            foo.sh        #  <-- script files for use with the script resource
        vars/             #
            main.yml      #  <-- variables associated with this role
        defaults/         #
            main.yml      #  <-- default lower priority variables for this role
        meta/             #
            main.yml      #  <-- role dependencies
        library/          # roles can also include custom modules
        module_utils/     # roles can also include custom module_utils
        lookup_plugins/   # or other types of plugins, like lookup in this case

    webtier/              # same kind of structure as "common" was above, done for the webtier role
    monitoring/           # ""
    fooapp/               # ""
#+end_src

- Library/mymodule.yml Pour stocker les modules et plugins.
- defaults/main.yml variables par defaut pour le role (peut être facilement) et inventory variables.
- vars/main.yml : other vars
- files/main.yml : fichiers deployés lors du role
- template : modèle que le role déploie
- meta les metadata du role / dependances
***   Tasks
Pour intégrer d'autre fichiers dans le dossier "tasks", il suffit. Grâce à import_tasks: file.yml
*** Placement des roles
Placement par defaut des roles :
~/.ansible/roles:/usr/share/ansible/role:/etc/ansible/roles
Placement dans un playbook:
    folder: roles

- L'indication dans le playbook
  #+begin_src
roles:
 -role:'/path/to/the/role'
  #+end_src

**** Utilisation
- avec l'option 'role' dans playbook(methode classique)
- Dans l'option 'tasks' avec l'argument 'include_role'
- Pareil qu'au dessus, en changeant 'include' par 'import'.
***** Include
L'inclusion permet une réutilisation du role
 - l'importance de cette inclusion est dans l'execution du play, ça permet à une tâche de s'executer avant.
   #+begin_src
tasks:
 -name: test
 include_role:
  name: role_test
   #+end_src
***** Import

* Artifacts
L'artifact est un fichier généré lors de l'execution d'un programme Ansible, il décrit se que fait le programme et donne des informations spécifiques. Nous pouvons voir ça comme une photo prise à l'instant T.
* Collections
** requirements files
#+begin_src yaml
#requirement.yaml
---
collections:
# With just the collection name
- my_namespace.my_collection

# With the collection name, version, and source options
- name: my_namespace.my_other_collection
  version: ">=1.2.0" # Version range identifiers (default: ``*``)
  source: ... # The Galaxy URL to pull the collection from (default: ``--api-server`` from cmdline)
#+end_src

*    Exemples
Afficher distribution du serveur
#+begin_src yml
---
- name: Exemple d'utilisation des facts
  hosts: localhost
  tasks:
    - name: Afficher la distribution Linux
      debug:
        var: ansible_facts['ansible_distribution']

#+end_src

*   Mots clés
~become: yes~ execute as root

* Alex
1. Créer des playbooks
2. Maîtriser les Buildin copy et config de fichiers
3. Installer un tuc
4. Config un serveur DNS
